### PR TITLE
Create gtk-hfm.go

### PR DESCRIPTION
**Pull request by hfmrow**
I don't know how to publish, always got "publishing not permitted"
then i put these functions here ...
please read comments before all, As i said, I cannot do in right way for publishing ... I let you to organize all.
All function are working, i will publish an example to include to your project in some days (if your wish).

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
Okay, so usually, when there is problems in a PR, you have to fix them yourself. Whoever reviews your PR, in this case that will be me, will tell you what's wrong. This will also help you increasing your knowledge and skills with git, GitHub and whatnot.

So, you have created a file called `gtk-hfm.go`, it contains your own name, that's not so good. The way the files are organized is by library (gtk, gdk ...). Each file is either called like the library (for example `gtk.go) or like an object type (for example `window` or `button`

So when you just add new GTK bindings, you could put them into `gtk.go`, assuming that they are compatible with all supported GTK versions. If your bindings are only available starting from GTK 3.22 for example, you'd have to add them to `gtk_since_3_22.go`. If you are adding a binding for a function that has been removed in 3.22, you'd have to put it into `gtk_deürecated_since_3_22.go` instead.

To see whether your implemented bindings need to be put in a specific file, instead of the general `gtk.go` one, you can either check the documentation or the GTK changelogs / commit history, since sadly the documentation rarely contains information about when something was added.

On top of that, please avoid adding code that is commented because it doesn't work. If it doesn't work, create an issue for it, requesting help or just leave it out.

**Comment by Bios-Marcel** [comment]
Oh and it appears there is something wrong in your code, likely a problem with the GTK version (what I mentioned in my previous comment).

```
could not determine kind of name for C.gtk_text_buffer_insert_markup
```

This avoids successful compilation.

**Comment by Bios-Marcel** [comment]
Oh, and yes, examples are always appreciated. They help new users of the library and they allow simple and fast testing.

**Comment by hfmrow** [comment]
Wow. many rules to be useful.
Forget everything, I do not want to waste my time to answer all your requests.
if you want to add these functions to your code, do it, otherwise do not do it.
Have a good day. Goodbye.
For information https://developer.gnome.org/gtk3/stable/GtkTextBuffer.html#gtk-text-buffer-insert-markup
And this function work well, i use it ...

**Comment by Bios-Marcel** [comment]
Yes, rules are useful, since rules exist in order to ensure that order is kept. And if properly contributing to a project is `a waste of time to you`, then you haven't understood the spirit of open source software.

**Comment by hfmrow** [comment]
Your right rules are useful, but i don't want to follow them.
Sure, I don't want conflict with you.
Take a look here: https://hfmrow.yo.fr/
it's my products for free world (open source ...), not big but this is that it could be. And you can notice most of program use your gotk3 project.
I'm sorry, don't know how to publish, to know version about function is implemented (gtk version), know how to add properly my contribution to open source project. But i would want to do it, Thank for your notifications about my contribution but without take down open source, i just want to give you some adds to your project, nothing more.
I'm French, some english subtleties aren't know for me, so try to understand each words as these would say.

**Comment by Bios-Marcel** [comment]
What do you mean by `publish`? Are you talking about some GitHub feature?

Anyway, check this out: https://developer.gnome.org/gtk3/stable/GtkTextBuffer.html

This is the documentation for the `GtkTextBuffer`. On that page, you can see all properties and functions offered by that type. One of them is `gtk_text_buffer_insert_markup`. Just search it via <kbd>Ctrl</kbd>-<kbd>F</kbd>. At the bottom you can see `Since 3.16`, meaning that the functionm has been added in GTK version `3.16`. Meaning that all versions that are GTK 3.14 or lower will not be able to compile any coding referring to `gtk_text_buffer_insert_markup`. Therefore the function needs to be moved into the file `gtk_since_3_16.go`.

That's how you could resolve the compilation issues for starters.

On top of the general documentation page, there is also this page: `https://developer.gnome.org/gtk3/3.22/api-index-3-16.html`, which lists all new symbols added with version `3.16`. Such an overview exists for every minor GTK release (3.12, 3.14, 3.16 ...).

**Comment by hfmrow** [comment]
Thank for clarification, i notice it now.
But it's your job to do it (placing, ideas, code in right place), I write code, not a documentation.
You and contributors are stone of this organization.
In fact, naming file with hfm is not ... but i use this name to add it to the project and use function as i wish ...
As I said before add these funct to project or not, it' your wish

**Comment by hfmrow** [comment]
Hi, sorry for my impetuosity.
Do you want the example I promised? the one using the functions that I submitted to you
It includes a lot of comments and was built using personal aids.
BUT I think this can be useful for beginners (when I was, I would have appreciated that ...).

**Comment by Bios-Marcel** [comment]
Before you submit examples, which you can submit to the gotk3-examples repo, you should first clean and fix your pull-request in the ways I have already told you. I am not trying to be an asshole here, but if we were to accept such PRs, it would set a bad example. And if more people were to do this, it would create unnecessary work.

**Comment by hfmrow** [comment]
Ok, clean, delete my actual pull request.
I will make a new pull request compliant with your ask. (maybe if time stay here).
Not sure.
Your arguments are well done, i approve that, but "fait chier quoi" sorry don't know how to tell this in English.
So next time i hope you accept my part for a free world (open source) with respect of your demands.
thanks for your time.

**Pull request closed without merging**
