### PR TITLE
Fixifaces2

### PR DESCRIPTION
**Pull request by olabini**
I've fixed up this as much as possible, but because I had to merge things inbetween, it wasn't possible to squash all commits.

The open question is whether we want the "impl" packages or a different naming.

### CODE REVIEW

**Comment by yamnikov-oleg** [comment]
It bothers me that 5 different packages are named all the same. As soon as calling impl functions is inevitable, this fact will either make user's code less readable (is `impl.WindowNew()` calling for gtk or gdk or something else?) or make packages inconvenient to use (using multiple impl packages requires renaming them in import statement).

I propose something about these variants:
* `gtk_impl` or `gtki` or...
* `gtk_func` or `gtkf` since impl packages would only be used for exported functions. Or...
* `gtk_call` since impl packages are considered to contain *direct calls* to the library.

**Comment by olabini** [comment]
Sure, I agree. I just couldn't come up with something nice. I'll go with gtkf etc.

**Comment by olabini** [comment]
Rename done.

**Comment by olabini** [comment]
I have added a final new pull request where all the changes are in one single commit. Closing this one.

**Pull request closed without merging**
