### PR TITLE
Fix ExpanderNew() not using the passed label (resolves #607)

### LINKED ISSUE #607: [BUG] ExpanderNew() ignores the passed label
**Describe the bug**
ExpanderNew() doesn't make use of the passed `label string`.

PR comes soon.

### PR DESCRIPTION
**Pull request by yktoo**

### CODE REVIEW

**Comment by yktoo** [comment]
Compilation with Go 1.9 [failed](https://travis-ci.com/github/yktoo/gotk3/jobs/352141952) with:
```
gtk/gtk.go:4061: cannot use _Cfunc_CString(label) (type *C.char) as type *C.gchar in assignment
```

All other Go versions succeeded. Can anyone advice on how this is to be fixed?

**Comment by MJacred** [comment]
In Go 1.9 and earlier, Go cannot auto-cast your value

you need to cast it to `(*C.gchar)` before passing it to `cstr`. `C.CString()` returns a value of type `*C.char`

**Comment by yktoo** [comment]
Ready for merge.

**Comment by MJacred** [comment]
could you do a squash, please?

thanks in advance

**Comment by yktoo** [comment]
[Done](https://travis-ci.com/github/yktoo/gotk3/builds/172634825).

**Pull request merged**
