### PR TITLE
Add support for GSettings and related things

### PR DESCRIPTION
**Pull request by olabini**

### CODE REVIEW

**Comment by andre-hub** [comment]
question: this GSettings is a subset in gio

can we move this commit to https://github.com/gotk3/gio ?

**Comment by olabini** [comment]
Sure. It's just we have a bunch of gio things in glib, which is why I put it here

**Comment by andre-hub** [comment]
i will remove for new subsets the double naming in url (gotk3/gotk3)

old path:

https://github.com/gotk3/gotk3
  -> cairo
  -> gdk
  -> glib
  -> gtk
  -> pango

e.g. https://github.com/gotk3/gotk3/glib

the new path:
   https://github.com/gotk3/glib

**Comment by olabini** [comment]
Wow, that's going to be breaking for anyone using it.

**Comment by olabini** [comment]
Incidentally, the gio package doesn't build.

**Comment by andre-hub** [comment]
actual not for existis functions / objects

this is only for new subsets

**Comment by olabini** [comment]
not sure I understand.

**Comment by olabini** [comment]
Can you let me know when the gio package actual works? Right now I needed the gsettings, but it seems like everything is currently in flux.

**Comment by olabini** [comment]
Actually, can we reopen this and merge it for now? the gotk3/gio package is not even close to compiling yet.

**Comment by andre-hub** [comment]
the gio package need more time for fixing ....

**Pull request merged**
