### PR TITLE
add GdkKeymap bindings

### LINKED ISSUE #384: Missing gdk_keymap_translate_keyboard_state()
GTK app receive different keyboard codes for different keyboard layouts. For example my keyboard have english and russian layouts and so my russian key "Я" (1745) is at "Z" (122).
I want to use keyboard shortcuts (like Ctrl+Z/Ctrl+C/Ctrl/V and etc) in my GTK-3 app for any possible languages.

gdk_keymap_translate_keyboard_state() can be better then my "GTK_TranslateKeyLayoutEnglish"
```
func main_event_listener(event *gdk.Event){
    eventObject := &gdk.EventKey{event}
    key := eventObject.KeyVal()
    state := eventObject.State()
    key, state = GTK_TranslateKeyLayoutEnglish(key, state)
    if state == gdk.GDK_CONTROL_MASK {
        if key == gdk.KEY_z {
            //Ctrl+Z
        } 
        if key == gdk.KEY_c {
            //Ctrl+C
        }
        if key == gdk.KEY_v {
            //Ctrl+V
        }
    } else {
        if key == gdk.KEY_F5 {
            //F5
        }
        if key == gdk.KEY_Delete {
            //Delete
        }
    }
}

func GTK_TranslateKeyLayoutEnglish(key uint, state uint) (uint, uint) {
    key2 := key
    state2 := state
    if state2 > 8192 { //RUSSIAN Ctrl 8196 == English Ctrl 4
        state2 -= 8192
    }
    switch key {
    case gdk.KEY_Cyrillic_ya: //RUSSIAN 'я'
        key2 = gdk.KEY_z
    case gdk.KEY_Cyrillic_ef: //RUSSIAN 'ф'
        key2 = gdk.KEY_a
    case gdk.KEY_Cyrillic_che: //RUSSIAN 'ч'
        key2 = gdk.KEY_x
    case gdk.KEY_Cyrillic_es: //RUSSIAN 'с'
        key2 = gdk.KEY_c
    case gdk.KEY_Cyrillic_em: //RUSSIAN 'м'
        key2 = gdk.KEY_v
        //etc
    }
    return key2, state2
}
```

### PR DESCRIPTION
**Pull request by MJacred**
bindings for
* gdk_keymap_translate_keyboard_state() 
* gdk_keymap_get_for_display()
* gdk_keymap_have_bidi_layouts()
* gdk_keymap_get_caps_lock_state()
* gdk_keymap_get_num_lock_state()
* gdk_keymap_get_modifier_state()
* for gdk_keymap_get_scroll_lock_state()

fixes #384

### CODE REVIEW

**Comment by SilentGopherLnx** [comment]
Great! I waited this... But how I can use it?

// Not work =(
func translate(key uint, state uint) (uint, uint) {
	d,_ := gdk.DisplayGetDefault()
	keymap, _ := d.GetKeymap()
	_ key20, _, _, state20 := keymap.TranslateKeyboardState(key, gdk.ModifierType(state), 0)
	key2 := *key20
	state2 := uint(*state20)
	return key2, state2
}

**Comment by MJacred** [comment]
Hi

* please read the official documentation: https://developer.gnome.org/gdk3/stable/gdk3-Keyboard-Handling.html#gdk-keymap-translate-keyboard-state
* please check if  `gdk.DisplayGetDefault()` returns an error.
* it is unclear what's written in `key` and `state`
* you should check if `key20` is nil
* you should check if `TranslateKeyboardState()` returns `true` or not
* `state` should be of type gdk.ModifierType -> you can use the values directly, see struct `ModifierType` in file gotk3/gdk/gdk.go

there are explanations on the web
* https://www.rdocumentation.org/packages/RGtk2/versions/2.20.31/topics/gdkKeymapTranslateKeyboardState
* https://mail.gnome.org/archives/gtk-vnc-list/2008-November/msg00003.html

if nothing helps, please provide a complete example (that can be compiled without adding any code from the tester side) and post it as a new issue. If you do, please use the proper markdown tags for your code. See https://guides.github.com/features/mastering-markdown/ chapter **Syntax highlighting** -> use `go` as language identifier for syntax highlighting

**Comment by SilentGopherLnx** [comment]
I need replace **translate_old** to **translate_new**
```go
package main

import (
	"fmt"

	"github.com/gotk3/gotk3/gdk"
	"github.com/gotk3/gotk3/gtk"
)

func main() {
	gtk.Init(nil)
	win, _ := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	win.Connect("key-press-event", func(win *gtk.Window, ev *gdk.Event) {
		main_event_listener(ev)
	})
	win.ShowAll()
	for {
		gtk.MainIteration()
	}
}

func main_event_listener(event *gdk.Event) {
	eventObject := &gdk.EventKey{event}
	key := eventObject.KeyVal()
	state := eventObject.State()

	//key, state = translate_old(key, state) // works with a,z,x,c on Russian language keyboard layout
	key, state = translate_new(key, state) // should works with any language and with all keyboard chars

	if state == gdk.GDK_CONTROL_MASK {
		if key == gdk.KEY_a {
			fmt.Println("Ctrl+A")
		}
		if key == gdk.KEY_z {
			fmt.Println("Ctrl+Z")
		}
		if key == gdk.KEY_c {
			fmt.Println("Ctrl+C")
		}
		if key == gdk.KEY_v {
			fmt.Println("Ctrl+V")
		}
	} else {
		if key == gdk.KEY_F5 {
			fmt.Println("F5")
		}
		if key == gdk.KEY_Delete {
			fmt.Println("Delete")
		}
	}
}

func translate_old(key uint, state uint) (uint, uint) {
	key2 := key
	state2 := state
	if state2 > 8192 { //RUSSIAN Ctrl 8196 == English Ctrl 4
		state2 -= 8192
	}
	switch key {
	case gdk.KEY_Cyrillic_ya: //RUSSIAN 'я'
		key2 = gdk.KEY_z
	case gdk.KEY_Cyrillic_ef: //RUSSIAN 'ф'
		key2 = gdk.KEY_a
	case gdk.KEY_Cyrillic_che: //RUSSIAN 'ч'
		key2 = gdk.KEY_x
	case gdk.KEY_Cyrillic_es: //RUSSIAN 'с'
		key2 = gdk.KEY_c
	case gdk.KEY_Cyrillic_em: //RUSSIAN 'м'
		key2 = gdk.KEY_v
		//etc
	}
	return key2, state2
}

func translate_new(key uint, state uint) (uint, uint) {
	d, err1 := gdk.DisplayGetDefault()
	if err1 != nil {
		fmt.Println("Display" + err1.Error())
	}
	keymap, err2 := d.GetKeymap()
	if err2 != nil {
		fmt.Println("GetKeymap" + err2.Error())
	}

	fmt.Println("Before")
	_, key20, _, _, state20 := keymap.TranslateKeyboardState(key, gdk.ModifierType(state), 0) // panic: runtime error: invalid memory address or nil pointer dereference
	fmt.Println("After")

	key2 := *key20
	state2 := uint(*state20)
	return key2, state2
}
```

**Comment by SilentGopherLnx** [comment]
ok... I'm stupid. I found solution. I don't need "keymap.TranslateKeyboardState()".

I need this https://github.com/gotk3/gotk3/pull/560

func (v *EventKey) HardwareKeyCode() uint {
c := v.native().hardware_keycode
return uint(c)
}

**Comment by MJacred** [comment]
Please don't create such a pull request...

You only need to create one single commit with that change.

Furthermore, the return value should be a `uint16` value.

**Pull request merged**
