### PR TITLE
Don't merge until publication of Golang v1.16: GtkAccelKey v1.16 issue fix

### PR DESCRIPTION
**Pull request by hfmrow**
## Please do not merge this PR until the official release of the public version of Golang 1.16.
_As the current version of Golang 1.16 is still in beta (until February), further changes can be added until its public release._

This PR fixes the problem with the GtkAccelKey declaration described below.
Its purpose is to help users, like me, who want to test future v1.16 functionality, while using the gotk3 library, and to facilitate discussion about this to make this solution the best it can be for everyone.

#### GtkAccelKey and Golang 1.16 issue
altered file: 'accel.go'

Golang 1.16 - Cgo changes [Go 1.16 Release Notes - The Go Programming Language](https://tip.golang.org/doc/go1.16#cgo):
The cgo tool will no longer try to translate C struct bitfields into Go struct fields, even if their size can be represented in Go. The order in which C bitfields appear in memory is implementation dependent, so in some cases the cgo tool produced results that were silently incorrect.

'C' struct definition:

```c
struct GtkAccelKey {
  guint           accel_key;
  GdkModifierType accel_mods;
  guint           accel_flags : 16;
};
```

Cgo compilation errors:

```bash
../../gotk3/gotk3/gtk/accel.go:264:5: val.accel_flags undefined (type _Ctype_struct__GtkAccelKey has no field or method accel_flags)
../../gotk3/gotk3/gtk/accel.go:273:22: obj.accel_flags undefined (type *_Ctype_struct__GtkAccelKey has no field or method accel_flags)
```

Solution:
Need new declaration for GtkAccelKey structure that does not explicitly access to 'accel_flags'.
'accel_flags' value remain accessible using bitwise operations.

### CODE REVIEW

**Comment by rubiojr** [comment]
I just hit this, thanks for documenting it.

**Comment by rubiojr** [comment]
@hfmrow doesn't seem 1.16rc1 changed anything that would affect this. What would be the downside (if any) of merging this now before 1.16 GM is released?

**Comment by essial** [comment]
It's released now.

**Comment by hfmrow** [comment]
dropped and [re-post](https://github.com/gotk3/gotk3/pull/730)
Sorry for the inconvenient.

**Pull request closed without merging**
