### PR TITLE
gtk_selection_data_set & gtk_drag_set_icon_pixbuf

### PR DESCRIPTION
**Pull request by BigFartTheory**
look there https://github.com/gotk3/gotk3/issues/327
and pull THIS first https://github.com/gotk3/gotk3/pull/328

usage example:
t_uri, _ := gtk.TargetEntryNew("text/uri-list", gtk.TARGET_OTHER_APP, 0)
evBox.DragSourceSet(gdk.GDK_BUTTON1_MASK, []gtk.TargetEntry{*t_uri}, gdk.ACTION_COPY)

evBox.Connect("drag-begin", func(g *gtk.EventBox, ctx *gdk.DragContext) {
fmt.Println("drag-begin")
pixbuf := .....
gtk.DragSetIconPixbuf(ctx, pixbuf, 0, 0)
})

evBox.Connect("drag-data-get", func(g *gtk.EventBox, ctx *gdk.DragContext, data_pointer uintptr, _ uint, _ uint) {
fmt.Println("drag-data-get")
cmd := "file://" + "/mnt/dm-1/testfile.txt" + "\n"
gtk.SetData(data_pointer, gdk.SELECTION_TYPE_STRING, []byte(cmd))
})

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
Is there any reason you are splitting the PR into two PRs asking for one of them to be pulled first?

**Comment by BigFartTheory** [comment]
Sorry. I just changed 2 files. I'm newbie

**Comment by Bios-Marcel** [comment]
just close and pr and merge the changes into one.

**Comment by SilentGopherLnx** [comment]
Is this code ok?

**Pull request merged**
