### PR TITLE
Rebase complete interface fixing, and merge latest changes on master

### PR DESCRIPTION
**Pull request by olabini**
Final and complete rebasing.

### CODE REVIEW

**Comment by olabini** [comment]
This one should merge cleanly - anyone has any more comments or are we OK with this?

**Comment by juniorz** [comment]
LGTM.

**Comment by andre-hub** [comment]
I am still at odds with the change. gotk should be a simple binding. Although the interfaces are nice, but I would not like to separate directories have it.
I have many other looked golang to c bindings in the last few days and so far I've seen none of which has an extra directories for interfaces.

**Comment by olabini** [comment]
OK, understood. None of the other C bindings have interfaces because none of them are interested in making it possible to test applications. But if you're not interested in this change, it won't happen.

My team will have to discuss if we should fork gotk3, since we have several thousand lines of code that are impossible to test without something like this.

**Pull request closed without merging**
