### PR TITLE
Fix TreeSelection.GetSelected interface (#94)

### PR DESCRIPTION
**Pull request by axel-freesp**
Made the interface more Go like, fix issue with the old implementation.

### CODE REVIEW

**Comment by axel-freesp** [comment]
I see: returning a pointer to TreeIter is better, it even makes user code smarter.

What about
```_, it, ok := ts.GetSelected()```
if you want to omit the model?

Usually, you want to have the model, either it is pre-defined as a global variable (no good style), or - if you have multiple models connected - it comes with the callback.

So I will provide a patch for the pointer return type.

**Comment by andre-hub** [comment]
i think this way is good the change to high level return values (go interfaces and types).
The go application don't need the pointer.
or what i overlooked?

**Comment by andre-hub** [comment]
what is with the code?

```go
func (v *TreeSelection) GetSelected() (model ITreeModel, iter *TreeIter, ok bool) {
	var cmodel *C.GtkTreeModel
	var citer C.GtkTreeIter
	c := C.gtk_tree_selection_get_selected(v.native(), &cmodel, &citer)
	model = wrapTreeModel(wrapObject(unsafe.Pointer(cmodel)))
	iter = &TreeIter{citer}
	ok = gobool(c)
	return
}
```


and on the application side:
```go
	model, iter, ok = selection.GetSelected()
	if ok {
		tpath, err := model.(*gtk.TreeModel).GetPath(iter)

```

**Comment by axel-freesp** [comment]
Hi,

returning a pointer to a tree iterator object is better than returning a copy of that object. Recall we want to re-write the API to have interfaces - the tree iterator object would turn into a tree iterator interface...

If there are no further objections, I will make the discussed changes now.

Cheers
Axel

**Pull request merged**
