### PR TITLE
Added OpenGL Context & Area

### PR DESCRIPTION
**Pull request by drakbar**
Added GLArea widget. In order to draw to the GLArea an OpenGL binding for go such as go-gl still needs to be used. I have an example that I will add to gotk3-examples if this is approved.

### CODE REVIEW

**Comment by andre-hub** [comment]
Hello @drakbar 

please check the travis-ci log. you need a version tag for the new function

**Comment by drakbar** [comment]
Hi @andre-hub 

I am not currently at my dev machine, and don't want to edit the files and have travis-ci fail and send out an alert.

> you need a version tag for the new function

According to developer.gnome.org [GLContext ](https://developer.gnome.org/gdk3/3.16/api-index-3-16.html)and [GLArea ](https://developer.gnome.org/gtk3/3.16/api-index-3-16.html)were added in 3.16.
I am not sure if the following changes will work and are what you had in mind? 

### GDK

**Remove** from `gdk/gdk.go`
```go
{glib.Type(C.gdk_gl_context_get_type()), marshalGLContext},
```
**Add** to `gdk/glcontext.go`
```go
// +build !gtk_3_6,!gtk_3_8,!gtk_3_10,!gtk_3_12,!gtk_3_14

...

func init() {

  tm := []glib.TypeMarshaler{
    {glib.Type(C.gdk_gl_context_get_type()), marshalGLContext},
  }

  glib.RegisterGValueMarshalers(tm)
}
```
**Add** to `gdk/gdk.go.h`
```c
#ifdef __GDK_GL_CONTEXT_H__

static GdkGLContext *
toGdkGLContext(void *p)
{
  return (GDK_GL_CONTEXT(p));
}

#endif
```

### GTK

**Remove** from `gtk/gtk.go`
```go
{glib.Type(C.gtk_gl_area_get_type()), marshalGLArea},

...

"GtkGLArea":              wrapGLArea,
```
**Add** to `gtk/glarea.go`
```go
// +build !gtk_3_6,!gtk_3_8,!gtk_3_10,!gtk_3_12,!gtk_3_14

...

func init() {

  tm := []glib.TypeMarshaler{
    {glib.Type(C.gtk_gl_area_get_type()), marshalGLArea},
  }

  glib.RegisterGValueMarshalers(tm)

  WrapMap["GtkGLArea"] = wrapGLArea
}
```
**Add** to `gtk/gtk.go.h`
```c
#ifdef __GTK_GL_AREA_H__

static GtkGLArea *
toGtkGLArea(void *p)
{
  return (GTK_GL_AREA(p));
}

#endif
```

**Comment by drakbar** [comment]
I have tested this on my local branch and it appears to work. Gonna push a commit now.

**Comment by drakbar** [comment]
According to [Dave Cheney](https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool) my build tags were not separated from the rest of the code by a new line. I have tested this new swath of changes on Ubuntu 18.10 amd64 which is the same target platform as the Travis-CI, so I am pretty confident that this should work.

**Comment by drakbar** [comment]
Closing to refactor file structure

**Pull request closed without merging**
