### PR TITLE
Update gbinding.go

### PR DESCRIPTION
**Pull request by CHchenf**
Modifying the above code can solve the error reporting problem of glib2 new version method

### CODE REVIEW

**Comment by sqp** [comment]
Here's the related glib changelog: [glib 2.67.1 changelog](https://gitlab.gnome.org/GNOME/glib/-/tags/2.67.1)

> Fix thread-safety of GBinding; see the updated documentation for g_object_bind_property() for full details — if your code uses GBinding across threads, you should re-check it against the latest documentation, use g_binding_unbind() rather than implicitly dropping the binding with your last g_object_unref() call, and use g_binding_dup_source()/g_binding_dup_target() instead of g_binding_get_source()/g_binding_get_target() (work by Sebastian Dröge) (!1745)

Documentation for new functions : [g-binding-dup-target](https://developer-old.gnome.org/gobject/stable/GBinding.html#g-binding-dup-target) and [g-binding-dup-source](https://developer-old.gnome.org/gobject/stable/GBinding.html#g-binding-dup-source)

I guess they don't require more resources to be freed so it should be fine to update. But we'll have to add flags to ensure we won't break those who still don't have at least version 2.67.1

**Comment by andre-hub** [comment]
@CHchenf and @sqp 

line 75:
origin
s := C.g_binding_get_source_property(v.native())

new
s := C.g_binding_get_target_property(v.native())

target or source?

so I mean that "source" belongs there. Is it a transmission error?
please fix this before we will merge.

**Comment by andre-hub** [comment]
and we need a flag for old and new glib versions

**Comment by hfmrow** [comment]
Hi,
I think it's a mistake.
If you check the declaration on line 89 (left side column), you will find the rightly defined binding 'GetTargetProperty'.
```go
func (v *Binding) GetTargetProperty() string {
	s := C.g_binding_get_target_property(v.native())
	return C.GoString((*C.char)(s))
}
```

so, this modification look like a careless mistake,
```go
func (v *Binding) GetSourceProperty() string {
	s := C.g_binding_get_source_property(v.native())
// 	s := C.g_binding_get_source_property(v.native())
	s := C.g_binding_get_target_property(v.native())
	return C.GoString((*C.char)(s))
}
```
#### and must be reversed to the previous statement version:
```go
func (v *Binding) GetSourceProperty() string {
	s := C.g_binding_get_source_property(v.native())
	return C.GoString((*C.char)(s))
}
```
`g_binding_get_source_property` and `g_binding_get_target_property` has been introduced in v2.26 [[ref1](https://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/gobject/GBinding.html#g-binding-get-source)], and not changed since (see ref2),
unlike `g_binding_dup_source` & `g_binding_dup_target` that recently introduced with v2.68. [[ref2]](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gobject/gbinding.h).

**Comment by sqp** [comment]
And I think we'd better either rename GetSource and GetTarget to DupSource and DupTarget, or inform that they now use their dup counterpart.
As those changes seem voluntarily breaking for code related to g_binding, and warned by the glib devs that their uses should be rechecked, I'd choose the rename on our side too. (I'm not sure those are widely used).

Could we add a "Changes" section in the package Readme to inform about those blocking changes?

### Breaking Changes
- **2021-08**: Glib version 2.68 deprecated **glib.Binding.GetSource** and **GetTarget** in favor of DupSource and DupTarget. Those using glib.Binding should check the [glib changes](https://gitlab.gnome.org/GNOME/glib/-/tags/2.67.1)

**Comment by hfmrow** [comment]
@sqp 
I agree, but a `CHANGE.md` file may be more efficient, no need to overload the ` README.md`.
Just a think about to how to tag an information (following your example):

- **2021-08**: Glib versions <= 2.66 now require the build tag **-tags "glib_2_66"**
- **2021-08**: Glib version 2.68 deprecated glib.Binding.GetSource and GetTarget in favor of DupSource and DupTarget. Those using glib.Binding should check the glib changes
---
`2021-08` does not indicate enough information. At PR writing time, the target version `release` is unknown, so, we cannot refer to it.
I'm trying to find a more precise way to indicate when exactly the change is effective.
Perhaps by providing a link to the relative pull request, like this ?
- **2021-08**: Glib version 2.68 deprecated glib.Binding.GetSource and GetTarget in favor of DupSource and DupTarget. Those using glib.Binding should check the glib changes. For those who use **_Glib versions <= 2.66_**, you now need to use the build tag **-tags "glib_2_66"**, see #826

or something else ?

**Pull request merged**
