### PR TITLE
Fix Paned.GetHandleWindow(): should return gdk.Window, not gtk.Window

### PR DESCRIPTION
**Pull request by MJacred**
See https://docs.gtk.org/gtk3/method.Paned.get_handle_window.html

### CODE REVIEW

**Comment by andre-hub** [comment]
Syntax typo?
return &gdk.Window{glib.Take(unsafe.Pointer(c))  **}**   , nil

wrapWindow ... How should this not be used?

**Comment by MJacred** [comment]
`wrapWindow` returns a **gtk**.Window  
but according to the docs, it should be a **gdk**.Window

a typo makes no sense. I literally copied and pasted it from a func further below.

see Viewport.GetBinWindow or Viewport.GetViewWindow

**Comment by andre-hub** [comment]
can you make a new PR?

**Comment by MJacred** [comment]
Sure. Give me a sec

And I just saw: even your revert failed: https://github.com/gotk3/gotk3/actions/runs/7753441381/job/21144754351?pr=914

**Pull request merged**
