### PR TITLE
added todos for missing bindings

### PR DESCRIPTION
**Pull request by MJacred**
* corrected comments where referenced func name was wrong (I assume copy-pasted binding code, but comment was not adjusted)
* added some missing enum values

added TODOs for missing bindings in
* GtkPopover
* GtkScrolledWindow
* GtkToolItem
* GtkToolButton
* GtkPlacesSidebar
* GtkColorChooserWidget
* GtkFontChooserWidget
* GtkContainer
* GtkImageMenuItem
* GtkFileChooserButton
* GtkBox
* GtkListBox
* GtkRadioMenuItem
* GtkExpander
* GtkAspectFrame
* GtkMenuItem
* GtkRecentChooserWidget
* GtkInfoBar
* GtkGrid
* GtkIconView
* GtkLayout
* GtkMenuShell
* GtkNotebook
* GtkStack
* GtkTextView
* GtkToolbar
* GtkToolItemGroup
* GtkToolPalette
* GdkKeymap
* GtkWidget
* GtkLabel
* GtkAccelLabel
* GtkDialog
* GtkImage
* GdkDisplay
* some for Cairo
* GtkCellView
* GtkEntry
* GtkSearchEntry
* GtkInputHints
* GtkEntryCompletion
* GtkSpinButton
* GtkCellEditable
* GtkBuildable
* GtkGLArea
* GtkRange
* GtkScale
* GtkInvisible
* GtkProgressBar
* GtkSwitch
* GtkToolShell
* GdkDisplayManager
* GdkDevice
* GdkSeat
* GdkPixbuf
* GdkRGBA
* GdkVisuals
* GdkAppLaunchContext

### CODE REVIEW

**Comment by MJacred** [comment]
@andre-hub: will stop adding todos for now. Should have almost everything in GTK+ (left out deprecated funcs since version 3.6 and before -> because gtk.go also has funcs added with version 3.6) and some of GDK

all merge conflicts were fixed. can be merged if travis pipeline is successful

**Comment by andre-hub** [comment]
@MJacred 
please for future work, can you create smaller pull request. smaller change can we faster merge.

**Comment by MJacred** [comment]
> @MJacred
> please for future work, can you create smaller pull request. smaller change can we faster merge.

yes, I'll keep that in mind.

**Comment by MJacred** [comment]
fyi: travis pipeline finished successfully (does not show like it's finished in the overview on this page, though -> at least for me)

**Pull request merged**
