### PR TITLE
PixbufAnimation gtk part

### PR DESCRIPTION
**Pull request by hfmrow**
gtk image functions relative to PixbufAnimation object:

gtk_image_get_animation()
gtk_image_new_from_animation()

### CODE REVIEW

**Comment by hfmrow** [comment]
Hi,
These functions (PixbufAnimation) allow to use gif images loaded as []byte to play animation properly.
Simple Pixbuf object does not allow this, the gifs loaded via it, still at the first image of the animation.

Below, a simple example, I will attach a gif image to this comment (referenced in the code).

```
package main

import (
	"io/ioutil"
	"log"

	"github.com/gotk3/gotk3/gdk"
	"github.com/gotk3/gotk3/gtk"
)

var img *gtk.Image

// Create and initialize the window
func setupWindow(title string) *gtk.Window {
	win, err := gtk.WindowNew(gtk.WINDOW_TOPLEVEL)
	if err != nil {
		log.Fatal("Unable to create window:", err)
	}

	win.SetTitle(title)
	win.Connect("destroy", func() {
		gtk.MainQuit()
	})
	win.SetPosition(gtk.WIN_POS_CENTER)
	win.SetDefaultSize(600, 300)

	box, _ := gtk.BoxNew(gtk.ORIENTATION_VERTICAL, 0)

	// Ze gif
	filename := "loading-horz.gif"
	// load gif as []byte
	data, _ := ioutil.ReadFile(filename)
	// Create a PixbufLoader to handle data
	pbLoader, err := gdk.PixbufLoaderNew()
	if err != nil {
		log.Fatalf("PixbufLoaderNew: %s\n", err.Error())
	}
	// Build a PixbufAnimation
	anim, err := pbLoader.WriteAndReturnPixbufAnimation(data)
	if err != nil {
		log.Fatalf("WriteAndReturnPixbufAnimation: %s\n", err.Error())
	}
	// Load PixbufLoader into an image object
	img, err := gtk.ImageNewFromAnimation(anim)
	if err != nil {
		log.Fatalf("ImageNewFromAnimation: %s\n", err.Error())
	}
	// Put image in the box
	box.Add(img)
	// And the box into the window ...
	win.Add(box)

	return win
}

func main() {
	gtk.Init(nil)

	win := setupWindow("Go Example PixbufAnimation")

	win.ShowAll()

	gtk.Main()
}

func ButtonClicked() {

}
![loading-horz](https://user-images.githubusercontent.com/45952208/67126365-261a8880-f1f7-11e9-9896-9ba19f7afdcd.gif)

```

**Comment by hfmrow** [comment]
@andre-hub 
Hi,
I don't understand why travis check fail, but it say "PixbufAnimation" does not exist ...
It's declared properly in gdk.go & linked in gdk.go.h ...
work well with my home-cloned version of gotk3.
An idea ?

**Comment by Bios-Marcel** [comment]
A retry probably won't help. I am assuming you forgot build tags for the gdk/gtk versions?

**Comment by hfmrow** [comment]
Hi, @Bios-Marcel thank for consideration.
I've checked version for new function (4 linked below), there is no specifications like since ...
and theoretically , the  structure PixbufAnimation does not require specific version (not indicated in gdk manual). Really i don't understand.

gdk_pixbuf_animation_new_from_file()
https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-Animations.html#gdk-pixbuf-animation-new-from-file

gdk_pixbuf_loader_get_animation()
https://developer.gnome.org/gdk-pixbuf/stable/GdkPixbufLoader.html#gdk-pixbuf-loader-get-animation

gtk_image_new_from_animation()
https://developer.gnome.org/gtk3/stable/GtkImage.html#gtk-image-new-from-animation

gtk_image_get_animation()
https://developer.gnome.org/gtk3/stable/GtkImage.html#gtk-image-get-animation

**Comment by Bios-Marcel** [comment]
Oh wait, dorry. I missread the error. It needs the gdk part of the go library, which isn't part of your commit and not already part of gotk either.

**Comment by Bios-Marcel** [comment]
Ypu should Make #448 and #449 one PR

**Comment by hfmrow** [comment]
Ok I try this

**Comment by hfmrow** [comment]
Thank you, next time i will care of the fact that travis don't check not yet merged PR before applying the tests ...

**Pull request closed without merging**
